services:

  pgdatabase: #custom name of choice
    image: postgres:13 #image
    environment: #environment variables
      - POSTGRES_USER="root"
      - POSTGRES_PASSWORD="root"
      - POSTGRES_DB="ny_taxi"
    volumes: #Volume Mappings https://docs.docker.com/storage/volumes/
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image:  dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  # pythonpipeline:
  #   # image: python:3.9.1
  #   build: .
  #   # volumes:
  #   #   - "ingest_data.py:ingest_data.py"
  #   # command:
  #   #   - "pip install pandas sqlalchemy psycopg2 pyarrow fastparquet wget"
  #   entrypoint: "python ingest_data.py --user=root --password=root --host=pgdatabase --port=5432 --db=ny_taxi --table_name=green_taxi_trips --url=https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2019-01.parquet"
  #   # working_dir: /app

